[workspace]
authors = ["Rohit Goswami <rgoswami@ieee.org>"]
channels = ["conda-forge"]
name = "metatomic"
platforms = ["linux-64"]
version = "0.1.0"

[environments]
docs = { features = ["docs"]}

[tasks]

[dependencies]
nushell = ">=0.110.0,<0.111"

[feature.docs.dependencies]
doxygen = ">=1.13.2,<2"
doxyrest = ">=2.1.2,<3"
lua = ">=5.4.8,<6"
tox = ">=4.34.1,<5"
